Task10/authentication
sanjar-kazakov/TestGuru pull request #16
Opened 2024-05-12 15:49 UTC by sanjar-kazakov

2024-05-12 15:56 UTC, sanjar-kazakov commented on app/views/shared/_navigation.html.erb
> +  <p><%= flash_message(:notice) %></p>
я не понимаю почему у меня не рендерится это сообщение хотя во флеше оно есть. Я нашел ответ, что это связано с турболинкс но так и не удалось пофиксить. 
<img width="1307" alt="image" src="https://github.com/sanjar-kazakov/TestGuru/assets/93393747/96b7d6ae-d854-4c5a-92ed-10d7db2ab01e">

2024-05-13 07:26 UTC, BubuntuClu requested changes

2024-05-13 07:26 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = test.current_user.new(test_params)
ты проверил этот код? что он делает?

2024-05-13 07:26 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @user = User.find(current_user.id)
у тебя в объекте `current_user` уже есть пользователь. не надо его еще раз искать

2024-05-13 07:26 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +  def flash_message(type)
если тебе нужно вывести все флэши, которые используются в твоем приложении, то как будет выглядеть вызов этого кода?
допустим, у тебя 3 флэша каких-то

```
flash_message(:alert)
flash_message(:notice)
flash_message(:info)
```
выглядит странно. как переделать код, чтобы не прописывать каждый флэш?

2024-05-13 07:26 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
роуты дубликаты

2024-05-13 07:26 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email", null: false
нужно добавить уникальный индекс на почту

2024-05-14 06:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    binding.pry
отладку надо выпиливать из кода. эта строчка убьет твое приложение в продакшене

2024-05-14 07:05 UTC, merged