Task 17/deploy
sanjar-kazakov/TestGuru pull request #32
Opened 2024-07-13 15:11 UTC by sanjar-kazakov

https://github.com/user-attachments/assets/3a554494-8121-4967-a837-da05ecdcbe79

2024-07-13 17:05 UTC, BubuntuClu commented on config/routes.rb
> +  get 'contact_forms/create'
дубли роутов на 21 строке

2024-07-13 17:05 UTC, BubuntuClu commented on db/migrate/20240703193649_add_index.rb
> +class AddIndex < ActiveRecord::Migration[6.1]
манипуляции над разными таблицами лучше в разные миграции помещать

зачем тебе индексы на эти поля?

2024-07-13 17:05 UTC, BubuntuClu commented on db/migrate/20240713090612_create_contact_forms.rb
> +    add_index :contact_forms, :phone_number
зачем на это поле индекс? почему добавление инедкса сделал вне блока создания таблицы?

2024-07-13 18:06 UTC, sanjar-kazakov commented on config/routes.rb
> +  get 'contact_forms/create'
Да, не заметил. 
Я сначала все сделал и назвал FedbackForm. А потом уже подумал, что это не то и начал заново переделывать. И видимо эти два роута автоматом добавились командой

2024-07-13 18:07 UTC, sanjar-kazakov commented on db/migrate/20240703193649_add_index.rb
> +class AddIndex < ActiveRecord::Migration[6.1]
То есть, если мне нужно будет добавить индекс на пяти сущностях разных таблиц, делать пять миграций?
Для чего? Чтобы по миграциям проще понимать было?

2024-07-13 18:08 UTC, sanjar-kazakov commented on db/migrate/20240703193649_add_index.rb
> +class AddIndex < ActiveRecord::Migration[6.1]
А на вопрос для чего мне на них индексы, я подумал, что по ним тоже часто может происходить вызовы.

2024-07-13 18:08 UTC, sanjar-kazakov commented on db/migrate/20240713090612_create_contact_forms.rb
> +    add_index :contact_forms, :phone_number
На него то же самое, что и с роутами.

2024-07-17 07:04 UTC, BubuntuClu requested changes

2024-07-17 07:04 UTC, BubuntuClu commented on db/migrate/20240703193649_add_index.rb
> +class AddIndex < ActiveRecord::Migration[6.1]
То есть, если мне нужно будет добавить индекс на пяти сущностях разных таблиц, делать пять миграций?
Для чего? Чтобы по миграциям проще понимать было?

да 5 разных миграций, чтобы в разработке можно было проще откатываться, чтобы в проде обновления происходили проще, не за раз все индексы генерились

2024-07-17 17:35 UTC, merged